### ISSUE TITLE
Npc respawn

### ISSUE THREAD

**Issue by manifex30890** [opentibiabr/forsaken-global#7]
there is a problem with npc because i don't have a single npc

**Comment by dudantas** [comment]
@manifex30890 fixed on https://github.com/opentibiabr/forsaken-global/commit/1702af1c7fd4a239c966fcf41740d69dc2536e0c, thanks for the report.

**Comment by manifex30890** [comment]
I downloaded server updates but cannot login now

**Comment by dudantas** [comment]
watch what you did wrong.
with the same modifications I was able to log in normally ... if necessary reinstall everything from scratch.
